---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    ## make ingress controller deployed on control plane only
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 1180
        hostPort: 1180
        listenAddress: 0.0.0.0
      - containerPort: 1543
        hostPort: 1543
        listenAddress: 0.0.0.0
      - containerPort: 30080
        hostPort: 30080
        listenAddress: 0.0.0.0
      - containerPort: 30443
        hostPort: 30443
        listenAddress: 0.0.0.0
  - role: worker
    extraPortMappings:
      - containerPort: 5432
        hostPort: 5432
        listenAddress: 0.0.0.0
      - containerPort: 3306
        hostPort: 3306
        listenAddress: 0.0.0.0
      - containerPort: 27017
        hostPort: 27017
        listenAddress: 0.0.0.0
      - containerPort: 8080
        hostPort: 8080
        listenAddress: 0.0.0.0
      - containerPort: 8443
        hostPort: 8443
        listenAddress: 0.0.0.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: 'node-role.kubernetes.io/worker: ""'
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry.local:5000"]
    endpoint = ["http://kind-registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."example.com"]
    endpoint = ["http://kind-registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."example.org"]
    endpoint = ["http://kind-registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."test.com"]
    endpoint = ["http://kind-registry.local:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."test.org"]
    endpoint = ["http://kind-registry.local:5000"]
